apiVersion: apps/v1
kind: Deployment
metadata:
  name: arjunptdemo
  labels:
    app: arjunptdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arjunptdemo
  template:
    metadata:
      labels:
        app: arjunptdemo
    spec:
      containers:
      - name: arjunptdemo
        image: arjunpt/democicd:1.0
        ports:
        - containerPort: 8080
